# Generated by Django 2.2 on 2021-01-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
